### ISSUE TITLE
What does ampersand mean in CSS embedding?

### ISSUE THREAD

**Issue by Multimegamander** [mint-lang/mint#291]
sorry for such a noob question, but something like; 

&:nth-child(1) {
      animation: line-scale 1s -0.4s infinite cubic-bezier(0.2, 0.68, 0.18, 1.08);
    }

what does that ampersand mean?

**Comment by s0kil** [comment]
@Multimegamander It simply is an easier way to nest selectors (similar to sass/scss nesting), example: https://sandbox.mint-lang.com/sandboxes/ks_pjnPKVGvmuA

**Comment by s0kil** [comment]
I missed the point of your question, the ampersand is related to CSS itself:
https://stackoverflow.com/a/49401539

In Mint instead of writing:
```css
p {
	color: red;	
}

p::after {
	margin: 1rem;
}
```
You can do:
```css
p {
	color: red;

	&::after {
		margin: 1rem;
	}
}
```
